{{- if .Values.sasl.enabled -}}
{{- if not .Values.sasl.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fluss.fullname" . }}-sasl-jaas-config
  labels:
    {{- include "fluss.labels" . | nindent 4 }}
type: Opaque
data:
  jaas.conf: {{ include "fluss.sasl.jaasConfig" . | b64enc | quote }}
{{- end -}}
{{- end -}}
